Added fail step
Signed-off-by: Kristin Brown <kristin.brown@solo.io>

diff --git a/.github/workflows/links.yml b/.github/workflows/links.yml
--- a/.github/workflows/links.yml
+++ b/.github/workflows/links.yml
@@ -205,6 +205,20 @@ jobs:
           chmod +x docs-link-checking/post-slack-results.sh
           docs-link-checking/post-slack-results.sh
 
+      - name: Fail check if errors exist
+        if: github.event_name == 'pull_request'
+        env:
+          ERRORS: ${{ steps.link-stats.outputs.errors }}
+        run: |
+          if [ "${ERRORS:-0}" -gt 0 ]; then
+            cat artifacts/agentgateway-oss-links.md >> "$GITHUB_STEP_SUMMARY"
+            echo "Link checker found ${ERRORS} error(s). See artifacts for details."
+            exit 1
+          else
+            echo "Link checker found ${ERRORS} errors."
+          fi
+
+
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
